# see: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  #- nightly
env:
  - PYTHON=""
install:
  - julia -e 'Pkg.clone("https://github.com/lruthotto/KrylovMethods.jl.git")'
  - julia -e 'Pkg.add("Conda")'
  - julia -e 'using Conda; Conda.add("mkl=2017"); Conda.add("matplotlib"); Conda.add("zlib=1.2.9")'
matrix:
  allow_failures:
    - julia: nightly
